### ISSUE TITLE
Pr2: la función `elMasViejo` no está hecha por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#11]
Esta es una práctica de recursión estructural. La idea es usar eso, y no encontrar formas especiales para cada función...
Solamente dejamos de usar recursión estructural cuando no se puede usar...

El secreto de programar bien no es cabecear los problemas, sino entender su estructura, y usar el tiempo para los casos que sí requieren mirarlos con cuidado...

**Comment by FernandoRoldan77** [comment]
Corregido el error de no hacer recursión estructural.

**Comment by fidel-ml** [comment]
Mucho mejor. Ahora, podrías usar una subtarea para elegir el mayor de los dos, y así no repetir el trabajo de llamar a la recursión...

**Comment by FernandoRoldan77** [comment]
> Mucho mejor. Ahora, podrías usar una subtarea para elegir el mayor de los dos, y así no repetir el trabajo de llamar a la recursión...

Agregada la subtarea sugerida.

**Comment by FernandoRoldan77** [comment]
> No estás usando recursión estructural. Básicamente seguís usando EL MISMO esquema que antes, pero pateaste el problema a una subtarea... USÁ recursión estructural. De yapa, te mandaste ALTO miedo al booleano en `esMayorA`...

Arregladas las 2 funciones en un solo commit, me,  complique de más por aplicar mal una subtarea.
