### ISSUE TITLE
Pr2: el nombre `cantipookemon` es inadecuado

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#13]
Los nombres deben describir el propósito de la función en forma aproximada. Y esta función es prácticamente igual a `contarPokemones` (y podrías prescindir completamente de una de ellas, usando la subtarea que ya estás usando...)

**Comment by FernandoRoldan77** [comment]
Corregido el error de tipeo en el nombre y corregida reutilizando un ejercicio anterior.
