### ISSUE TITLE
Pr2: el primer caso de `contarPokemonSegunTipo` es innecesario

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#14]
O bien usás subtareas, o bien analizás los casos... Pero si tu subtarea se encarga de todos los casos, ¿por qué mirar casos especiales por separado? Tenés una tendencia a tratar de hacer trabajo de más que te va a complicar mucho en el futuro si no la corregís...

**Comment by FernandoRoldan77** [comment]
> O bien usás subtareas, o bien analizás los casos... Pero si tu subtarea se encarga de todos los casos, ¿por qué mirar casos especiales por separado? Tenés una tendencia a tratar de hacer trabajo de más que te va a complicar mucho en el futuro si no la corregís...

Corregido el PM de más y delegada la responsabilidad en la subtarea.
