### ISSUE TITLE
Pr2: la función `asignadosPorProyecto` recorre la empresa muchas veces (en su subtarea `cantidadDeRolesPorProyecto`)

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#19]
Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by FernandoRoldan77** [comment]
Corregido el asignadoPorProyecto con una subtarea.

**Comment by fidel-ml** [comment]
Sigue igual. La idea no es tomar cada proyecto y contar todas las veces que aparece, sino hacer un recorrido por recursión estructural sobre los proyectos UNA SOLA VEZ.

**Comment by FernandoRoldan77** [comment]
> Sigue igual. La idea no es tomar cada proyecto y contar todas las veces que aparece, sino hacer un recorrido por recursión estructural sobre los proyectos UNA SOLA VEZ.

Cambiada la solución desde cero y agregada la corrección.

**Comment by fidel-ml** [comment]
Muchísimo mejor. Fijate que en el caso base estás devolviendo 0, pero tendrías que contar a ese proyecto... (Si no, cuando haya 3 me vas a decir que son 2, etc.)

**Comment by FernandoRoldan77** [comment]
> Muchísimo mejor. Fijate que en el caso base estás devolviendo 0, pero tendrías que contar a ese proyecto... (Si no, cuando haya 3 me vas a decir que son 2, etc.)

Listo, ya fue corregido el error.
