### ISSUE TITLE
La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#2]
La función `vieneDespues` definida no es la pedida. Por ejemplo, `Miercoles` viene después que `Lunes`, pero tu función no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by FernandoRoldan77** [comment]
Se corrigió siguiendo la recomendación con subtareas, opte por enumerar los días mediante una función para poder compararlas si venían después o no.

**Comment by fidel-ml** [comment]
Ojo que `sonDiasDespues` es innecesaria (porque se llama igual que la que te pedimos). Además, tiene "miedo al booleano"

**Comment by FernandoRoldan77** [comment]
Corregida con la devolución.
