### ISSUE TITLE
Pr2: la función `cantPokemon` hace doble PM

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#21]
Y al hacerlo, generás casos innecesarios.
O BIEN usás subtareas, O BIEN hacés recursión estructural y analizás los casos. ¿Para qué preguntar separado si la lista es vacía, cuando, primero, estás trabajando con un entrenador y no una lista, y segundo, se encarga la subtarea?

**Comment by FernandoRoldan77** [comment]
> Y al hacerlo, generás casos innecesarios. O BIEN usás subtareas, O BIEN hacés recursión estructural y analizás los casos. ¿Para qué preguntar separado si la lista es vacía, cuando, primero, estás trabajando con un entrenador y no una lista, y segundo, se encarga la subtarea?

Corregido con la sugerencia dada.
