### ISSUE TITLE
Pr2: `esMayorA` tiene ALTO miedo al booleano

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#22]
NUNCA uses un if-then-else para devolver True o False...

**Comment by FernandoRoldan77** [comment]
Ya corregido.

**Comment by fidel-ml** [comment]
Pero ahora no controla si es mayor, sino que devuelve al mayor, por lo que su nombre ya no es adecuado... :(

**Comment by FernandoRoldan77** [comment]
> Pero ahora no controla si es mayor, sino que devuelve al mayor, por lo que su nombre ya no es adecuado... :(

Corregido , en el apuro de corregir el error, olvidé de cambiar el nombre que declaraba  algo que ya no hacía.
