### ISSUE TITLE
Pr3: en `poner` podrías no usar recursión...

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#23]
Ya sé que es una práctica de recursión... Pero siempre es mejor usar las herramientas más simples disponibles. ;)

**Comment by FernandoRoldan77** [comment]
> Ya sé que es una práctica de recursión... Pero siempre es mejor usar las herramientas más simples disponibles. ;)

poner :: Color -> Celda -> Celda
poner color CeldaVacia               = (Bolita color CeldaVacia)
poner colorAgregado (Bolita c celda) = (Bolita c (Bolita colorAgregado celda))

Hola Fidel, yo  lo hice así, creo que no use recursión o hay algo que no estaría viendo.

**Comment by FernandoRoldan77** [comment]
Funcion simplificada.
