### ISSUE TITLE
Pr3: `ponerN` hace una recursión innecesaria

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#24]
¿Por qué las querés agregar sí o sí al final? Si lo hacés al principio, te ahorrás una recursión entera...
Por otra parte, ¿por qué reimplementar `poner` en `agregarNBolitas`? Tenés que recordar reutilizar código.

**Comment by FernandoRoldan77** [comment]
Arreglada con las sugerencias.
