### ISSUE TITLE
Pr3: `pasosHastaTesoro` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#25]
Básicamente, me decís que hay un tesoro en un mapa sin nada (`Fin`), pero eso no es cierto. La función es parcial (lo pide el enunciado).
Por otra parte, no es feliz llamar a operaciones recursivas sobre partes que no son partes recursivas del dato original. Podrías poner directamente el resultado en este caso...

**Comment by FernandoRoldan77** [comment]
> Básicamente, me decís que hay un tesoro en un mapa sin nada (`Fin`), pero eso no es cierto. La función es parcial (lo pide el enunciado). Por otra parte, no es feliz llamar a operaciones recursivas sobre partes que no son partes recursivas del dato original. Podrías poner directamente el resultado en este caso...

Corregido con la devolución dada.

**Comment by fidel-ml** [comment]
Mejor. Pero, ¿para qué usar `alMenosUnTesoro Fin`? SABÉS que siempre da error... Es un llamado innecesio a subtarea.

**Comment by FernandoRoldan77** [comment]
> Mejor. Pero, ¿para qué usar `alMenosUnTesoro Fin`? SABÉS que siempre da error... Es un llamado innecesio a subtarea.

Corregido.
