### ISSUE TITLE
Pr3: en `hayTesoroEn` las subtareas repiten mucho análisis de los mismos casos

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#26]
Básicamente, no está claro si usás recursión sobre el 1er argumento o sobre el 2do.
Es una forma complicada de doble PM... SIEMPRE elegí un parámetro para hacer recursión, y si es necesario en algún caso, lo hacés también para el otro (como en `zipMaximos`, por ejemplo). Esto lo vimos en clase...

**Comment by FernandoRoldan77** [comment]
> Básicamente, no está claro si usás recursión sobre el 1er argumento o sobre el 2do. Es una forma complicada de doble PM... SIEMPRE elegí un parámetro para hacer recursión, y si es necesario en algún caso, lo hacés también para el otro (como en `zipMaximos`, por ejemplo). Esto lo vimos en clase...

Arreglado y resuelto haciendo recursión sobre el número de pasos.
