### ISSUE TITLE
Pr3: `leaves` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#29]
Básicamente, devuelve todos los nodos...

**Comment by FernandoRoldan77** [comment]
Solucionada cambiando la implementación.

**Comment by fidel-ml** [comment]
La función `esHoja` tiene un nombre inadecuado, porque mira a dos subárboles, y no indica lo que dice respecto de ellos...
Por otra parte, en la rama del then tenés código innecesario, porque ya tenés información sobre los casos recursivos, y no la estás aprovechando...

**Comment by FernandoRoldan77** [comment]
> La función `esHoja` tiene un nombre inadecuado, porque mira a dos subárboles, y no indica lo que dice respecto de ellos... Por otra parte, en la rama del then tenés código innecesario, porque ya tenés información sobre los casos recursivos, y no la estás aprovechando...

Corregido.

**Comment by fidel-ml** [comment]
Mejor. Pero el nombre `verSiSonHojas` es poco adecuado, porque no mira si son hojas. Además, tiene demasiadas responsabilidades, porque tiene que hacer un doble PM... Como opciones, o hacés una función más simple que verifica algo para UN árbol, o agregás un caso especial en la función original (como hicimos con otras funciones de listas...)

**Comment by FernandoRoldan77** [comment]
> Mejor. Pero el nombre `verSiSonHojas` es poco adecuado, porque no mira si son hojas. Además, tiene demasiadas responsabilidades, porque tiene que hacer un doble PM... Como opciones, o hacés una función más simple que verifica algo para UN árbol, o agregás un caso especial en la función original (como hicimos con otras funciones de listas...)

Cambiada la función con un solo árbol como parámetro y el nombre poco adecuado.
