### ISSUE TITLE
La función `and` no pasa el test 

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#3]
La función `and` de la práctica 1 debería comportarse de la siguiente manera:
```
> and False (error "Mal")
False
```
Sin embargo, tu versión da `error "Mal"`.
Así, no es la función pedida.

**Comment by fidel-ml** [comment]
No. Esa era la explicación de cómo lo veía Haskell. La idea es que lo resuelvas haciendo PM solamente en el primer argumento (y sin caer en miedo al booleano).

**Comment by FernandoRoldan77** [comment]
Mm, porque yo lo había resuelto de esta forma y no estaría viendo mi error entonces, pensaba que se resolvía así porque el único caso que es True  es cuando son los 2 True  y al ser una conjunción todo lo demás siempre dará falso. 
and True True   = True
and _ _   = False

**Comment by fidel-ml** [comment]
El tema es que si el segundo argumento es `error ""` en `and False (error "")` y lo tiene que evaluar, entonces daría error y no `False`. Ahora bien, si vos decís que DEBE controlar que ambos sean `True` para elegir la primera ecuación, es natural pensar que tiene que mirar ambos. Sin embargo, la versión actual de Haskell no lo hace así, sino que los hace de a uno, lo que es confuso.

La idea es que no hagas doble PM a menos que sea imprescindible. Y en este caso no lo es. O sea, básicamente, en este ejemplo NO hace falta hacer PM sobre el 2do argumento. ¿Podés reescribirla así?

**Comment by FernandoRoldan77** [comment]
Por las dudas aviso que corregí hace unos días estas issues pendientes, pero no comente acá, ya que había tageado con el commit.

**Comment by fidel-ml** [comment]
Siempre respondé los issues, porque siendo tantos, yo miro los issues y no los commits... :)
