### ISSUE TITLE
Pr3: faltan funciones

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#31]
A saber: 
  * `listPerLevel`
  * `ramaMasLarga`
  * `todosLosCaminos`
  * `eval`
  * `simplificar`

**Comment by FernandoRoldan77** [comment]
Agregados todos menos simplificar que todavía estoy pensando como resolverlo.

**Comment by fidel-ml** [comment]
¿Probaste usar lo que estamos estudiando en esta práctica: RECURSIÓN ESTRUCTURAL? Suele servir usar el tema que corresponde a la práctica en cuestión... ;) JAJA

**Comment by FernandoRoldan77** [comment]
> ¿Probaste usar lo que estamos estudiando en esta práctica: RECURSIÓN ESTRUCTURAL? Suele servir usar el tema que corresponde a la práctica en cuestión... ;) JAJA

Jaja, ahí subí una resolución Fidel.

**Comment by FernandoRoldan77** [comment]
> > ¿Probaste usar lo que estamos estudiando en esta práctica: RECURSIÓN ESTRUCTURAL? Suele servir usar el tema que corresponde a la práctica en cuestión... ;) JAJA
> 
> Jaja, ahí subí una resolución Fidel, en el commit me comi el # y no se tageo el issue.

**Comment by FernandoRoldan77** [comment]
> ¿Probaste usar lo que estamos estudiando en esta práctica: RECURSIÓN ESTRUCTURAL? Suele servir usar el tema que corresponde a la práctica en cuestión... ;) JAJA

Jaja, ahí subí una solución a simplificar.

**Comment by fidel-ml** [comment]
Bien para el primer intento. Pero las subtareas tienen problemas, las 3.
Las dos primeras tienen muchos casos de menos. Y la última no está trabajando como se espera, porque no sigue el mismo esquema de las otras (AGREGAR el constructor correspondiente, cuando corresponde)...

**Comment by FernandoRoldan77** [comment]
> Bien para el primer intento. Pero las subtareas tienen problemas, las 3. Las dos primeras tienen muchos casos de menos. Y la última no está trabajando como se espera, porque no sigue el mismo esquema de las otras (AGREGAR el constructor correspondiente, cuando corresponde)...

Corregido agregando el caso faltante de suma , cuando se multiplica por 1 y la negación.

**Comment by fidel-ml** [comment]
Faltan aún casos en `simplificarSegunCriterioDeProducto`

**Comment by FernandoRoldan77** [comment]
> Faltan aún casos en `simplificarSegunCriterioDeProducto`

Agregado el caso faltante.
