### ISSUE TITLE
La función `or` es incompleta

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#4]
En la función `or`, falta un caso, Al corregirla, prestar atención para no cometer "miedo al booleano"...

**Comment by FernandoRoldan77** [comment]
Agregado el caso faltante.

**Comment by fidel-ml** [comment]
Fijate que ahora tenés "miedo al booleano", porque preguntás si el segundo argumento es `True` para devolver `True` y si es `False` para devolver `False`... ¿Podrías hacerlo sin tanta vuelta (y con menos ecuaciones)?

**Comment by FernandoRoldan77** [comment]
Listo, corregida con la devolución dada.

**Comment by fidel-ml** [comment]
Así como está, a la función `or` le falta un caso... (`or False True`).

**Comment by FernandoRoldan77** [comment]
Por las dudas aviso que corregí hace unos días estas issues pendientes, pero no comente acá, ya que había tageado con el commit.
