### ISSUE TITLE
Tenés subtareas con demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#5]
Idealmente, cada subtarea atiende a una única responsabilidad. Sin embargo, tareas como `contarSiEsDeTipo` está haciendo más de una cosa. Deberías dividirla en 2 subtareas, una para cada responsabilidad.

**Comment by FernandoRoldan77** [comment]
Se dividió en las subtareas recomendadas.

**Comment by fidel-ml** [comment]
Bien. Podrías prescindir de la función, pero no está mal así.
