### ISSUE TITLE
En general, debería evitarse el pattern matching múltiple

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#6]
La función `cantidadDePokemonDe` hace un pattern matching doble, sobre el `Entrenador` y sobre sus `Pokemon`. Lo ideal es que cada función realice un único pattern matching, para asegurar que tiene una única responsabilidad (delegando las demás a otras subtareas).

**Comment by FernandoRoldan77** [comment]
Arreglado el PM doble.

**Comment by fidel-ml** [comment]
La corrección es incorrecta, porque ahora no contempla todos los casos posibles... No deberías hacer un PM sobre el 2do argumento. 
La función `and` sigue igual, con doble PM

**Comment by fidel-ml** [comment]
Ahora la veo bien. Andá a saber qué miré... JE
