### ISSUE TITLE
Pr2: la función `reversa` no está hecha con recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [FernandoRoldan77/EstrD22s1#9]
Si bien no está mal utilizar subtareas, esta es una práctica de recursión estructural, y la idea es que las puedan hacer con recursión estructural, en aquellos casos que se pueda (como este).
Si la vas a hacer con subtareas, el primer caso es innecesario (porque está cubierto por el segundo).

**Comment by FernandoRoldan77** [comment]
Consulta Fidel, yo puse el siguiente código y puede ser que la corrección que me hiciste sea de otro ejercicio? Incluso me dijiste de subtareas que no estoy utilizando , por eso me entro la duda o no estaría viendo el error, ya que plante el caso base y el caso recursivo pero invertidos para que arme la lista de adelante para atrás.

reversa :: [a] -> [a]
reversa []      =   []
reversa (x:xs)  =   reversa xs ++ [x]

**Comment by fidel-ml** [comment]
Ah. Seguramente miré el código de alguien más... Es correcto tu código :-D
